import type { Metadata } from 'next'
import '@/styles/base/_global.scss'
import { Header } from '@/widgets/header/ui/Header'
import styles from './rootLayout.module.scss'
import { QueryProvider } from '@/shared/providers/queryProvider/ui/QueryProvider'
import { AuthSidebar } from '@/widgets/Sidebar/ui/AuthSidebar'

export const metadata: Metadata = {
  title: 'Unity Gram',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <Header />
          <div className={styles.layout}>
            <AuthSidebar />
            <main className={styles.main}>
              {children}
            </main>
          </div>
        </QueryProvider>
      </body>
    </html>
  )
}
