import createClient from "openapi-fetch";
import type {paths} from "@/shared/api/schema";
import {Middleware} from "openapi-fetch"; // generated by openapi-typescript


const authMiddleware: Middleware = {
    async onRequest({ request, options }) {
        return request
    },
    async onResponse({ request, response, options }) {

    },
    async onError({ error }) {

    },
};


const baseUrl: string = process.env.NEXT_PUBLIC_BASE_URL;
if (!baseUrl) throw new Error("NEXT_PUBLIC_BASE_URL is not defined");

export const client = createClient<paths>({
    baseUrl,
    headers: {},
});